# Generated by Django 4.1.6 on 2023-02-10 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Philanthropist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('accomplish_by', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DecimalField(decimal_places=2, max_digits=8)),
                ('spent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('philanthropist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ngo.philanthropist')),
            ],
        ),
        migrations.CreateModel(
            name='PhilanthropistPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philanthropist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.philanthropist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ngo.type')),
            ],
        ),
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.TextField()),
                ('end_goal', models.TextField()),
                ('mission', models.TextField()),
                ('history', models.TextField()),
                ('funding_needed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ngo.plan')),
                ('previous_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='ngo.work')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ngo.transaction')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ngo.type')),
            ],
        ),
    ]
