# Generated by Django 4.1.6 on 2023-02-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ngo_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ngo.ngo'),
            preserve_default=False,
        ),
    ]
