# Generated by Django 4.1.6 on 2023-02-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_rename_ngo_id_transaction_ngo_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='name',
            field=models.CharField(default='def', max_length=255),
            preserve_default=False,
        ),
    ]
