# Generated by Django 4.1.6 on 2023-02-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_ngo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='transaction',
        ),
    ]
