# Generated by Django 4.1.6 on 2023-02-11 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0007_ngo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='city',
            field=models.CharField(default='Pune', max_length=255),
        ),
        migrations.AlterField(
            model_name='philanthropistpreference',
            name='philanthropist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='ngo.philanthropist'),
        ),
    ]
