# Generated by Django 4.1.6 on 2023-02-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0011_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
