# Generated by Django 4.1.6 on 2023-02-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phalanthropist',
            field=models.BooleanField(default=False),
        ),
    ]
